### ISSUE TITLE
Python Refresher

### ISSUE THREAD

**Issue by MikeDulik** [ga-wdi-exercises/sweet-libs#1]
Comfort: 3

https://github.com/MikeDulik/Python-Refresher

The tutorial I went over was very basic.  The interview questions I found are really good though! The others on the site I referenced are great if yall ever need any =) They provide awesome explanations and multiple solutions.

I wanted to get a very basic refresher in; I need to work on some outcomes stuff.

**Comment by Curtismn87** [comment]
How refreshing is python?

**Comment by MikeDulik** [comment]
IT'S JUST SO REFRESHING!
-Ron Burgandy after he smokes crack on live TV in Anchorman 2
