### ISSUE TITLE
React-Team:Walker Texas Ranger- Nick, Preston

### ISSUE THREAD

**Issue by nolds9** [ga-wdi-exercises/sweet-libs#11]
Repo: https://github.com/nolds9/teach-yourself-react.js

Comfort: 4
Completeness: 5

FB: Would love to learn how to integrate React with Backbone. Specifically, how to have a react component tied to a BB model.

**Comment by mosesadg** [comment]
What is the advantage of using JSX?

**Comment by nolds9** [comment]
JSX at its core, provides syntactic sugar that allows HTML and JS to live side-by side without the browser inteferring. It's a lot cleaner and efficient than vanilla js in my opinion.
