### ISSUE TITLE
societ_io

### ISSUE THREAD

**Issue by robertbenjamin** [ga-wdi-exercises/sweet-libs#16]
comfort: 5

https://github.com/lanak94/teach_yourself_socket.io

Is it possible to use websockets as a replacement for AJAX to communicate with a database? Or is the connection solely user-to-user?

**Comment by alexbannon** [comment]
way to misspell socket doofus.

jk

**Comment by robertbenjamin** [comment]
@alexbannon no no this isn't socket.io, it's a new thing called societ

**Comment by alexbannon** [comment]
"societ-io...plug into life"

**Comment by robertbenjamin** [comment]
:+1:
