### ISSUE TITLE
Basic Angular 

### ISSUE THREAD

**Issue by M00staff** [ga-wdi-exercises/sweet-libs#18]
Comfort - 3

Sorry but I did tutorials all weekend so i wasn't starting from scratch, and figured this would be a really good way to hammer some things in.  

Its setup and makes an AJAX request to weather underground - very basic but it works! 

https://github.com/M00staff/AngularWhatUp

**Comment by Ryan-321** [comment]
So did you start with your controllers in app.js and then separate them out to make your file structure more clean?  

Did the tutorial this weekend to, was good stuff.

**Comment by nolds9** [comment]
Love the Readme.

Code is very well documented. :+1: 
 
Out of curiosity, I've seen different syntax's for defining the controller, do you know what the main difference is between ng-controller="myController" and ng-controller="myController as myModel"?

**Comment by englep10** [comment]
Very cool. I like the simplicity of the ajax call. Do you think that there would be any differences when using a private api key? Or would the figaro gem set up be about the same?

**Comment by M00staff** [comment]
I just split up the controllers to make sure each worked - it made more sense that way for bug fixing. 

As for the the ng-controller="myController as myModel" (I THINK) it assigns myModel as a variable (although they don't call it that - i think they call it an 'alias') so in the rest of the code you just say myModel.this and myModel.that.

**Comment by M00staff** [comment]
i used a private API key - it was really straightforward and awesome
