### ISSUE TITLE
Erica Andersen's 'Teach Yourself' Homework

### ISSUE THREAD

**Issue by andersenek** [ga-wdi-exercises/sweet-libs#25]
#### Team Meteor Shower
> Erica A. + Paul D.

**Erica's Repo:** https://github.com/andersenek/meteor-polls
**Demo:** http://wdipolls.meteor.com/

Comfort: 4.5/5
Completeness: 5/5

Comments: Meteor.js is awesome!

**Comment by adrianshep** [comment]
Very neat and elegant app! My third option ran over the character limit, though, and now embarrasses me. Any chance of an editing interface?

**Comment by leighvarley** [comment]
Neat that you can write the front-end, the back-end, and the database with nothing but JavaScript. I also find it interesting that one line of code can run on both the client and the sever and do different things in each environment. Thanks for all of the info and resources - I'm interested in checking this out!
