### ISSUE TITLE
Intro to PHP

### ISSUE THREAD

**Issue by malissaromero** [ga-wdi-exercises/sweet-libs#26]
Repo: https://github.com/malissaromero/teachyourself_php

Comfort Level: 5 

I wasn't able to see my code in my browser while I was going through the Treehouse tutorial. I tried to open index.php through the terminal and localhost/index.php straight into the browser. Am I missing something?

**Comment by RobertAKARobin** [comment]
You need to have an Apache server running on your computer. Take a look at the section about installing XAMPP here: https://github.com/ga-dc/pbj/tree/master/10-back-and-front-of-front-end/intro-to-php

**Comment by kristingreenslit** [comment]
Very cool! I'm looking forward to learning more about PHP. What steps did you take to get a server up and running?

**Comment by malissaromero** [comment]
@RobertAKARobin Hey, when you get a chance, let me know what I am doing wrong? I do have it running but I still cannot see index.php on my browser. This is running in my background: 

![screen shot 2015-09-08 at 2 29 46 pm](https://cloud.githubusercontent.com/assets/11203264/9743826/46ac5b98-5636-11e5-8d78-4ac898b23df3.png)

**Comment by kristingreenslit** [comment]
I don't know the first thing about PHP, but I got "hello world" to render in the browser by adding <?php include_once("home.html"); ?> to the top of the index.php file and opening home.html in the browser. 

<img width="808" alt="screen shot 2015-09-08 at 20 19 25" src="https://cloud.githubusercontent.com/assets/5890436/9750596/ef5761bc-5667-11e5-977e-11588f5a0095.png">
