### ISSUE TITLE
Learn Python

### ISSUE THREAD

**Issue by ashahry** [ga-wdi-exercises/sweet-libs#28]
https://github.com/ashahry/teach_yourself

**Comment by ashahry** [comment]
comfort Level: 4/5
Completeness: 4/5

**Comment by puzzleboks** [comment]
So, given the similarities between Javascript and Python, which one do you like to code in better?

**Comment by ktw1222** [comment]
Isn't it difficult to support larger programs and better code reuse for Python if it is not engaging in class definitions?

**Comment by tomBeach** [comment]
Did you find it difficult to adjust to the syntax differences between python and ruby? They seem very similar (from what I know about them at this point anyway). What are the major uses for python?
