### ISSUE TITLE
Blazing Saddles

### ISSUE THREAD

**Issue by karldonus** [ga-wdi-exercises/sweet-libs#29]
https://github.com/karldonus/mongoFirstAttempt

Comfort Level: 3

Observations: MongoDB isn't as bad as I thought. Took a while to get everything up and running. Mongoose certainly made things DRYer compared to the native mongodb driver.

**Comment by edwardpark** [comment]
there's something funny with your root callback on my initial load but other than that it looks great !

**Comment by puzzleboks** [comment]
So which database do you guys like the best? Mongo, Firebase, PostgresQL, or Sequelize. Good job.
