### ISSUE TITLE
Final HW submission

### ISSUE THREAD

**Issue by edwardpark** [ga-wdi-exercises/sweet-libs#30]
Comfort:4
Completness:4

I'm going to cry so much when everyone leaves.

https://github.com/edwardpark/MJS_itchy-octo

**Comment by arkinjb** [comment]
Can you explain the concept of Data on the Wire?

**Comment by leighvarley** [comment]
Great notes and nice to be able to see it deployed.
Also, cool that you had such an enlightening moment of realization that you must learn meteor.
