### ISSUE TITLE
Python/Django 

### ISSUE THREAD

**Issue by lscottcook** [ga-wdi-exercises/sweet-libs#35]
Link to repo: https://github.com/lscottcook/python_django

Comfort level: 3/4-  I did not focus on Python as much as I wanted to.  I focused more on learning Django

**Comment by iamjustinprice** [comment]
What ARE the benefits of coding in Python? :)
Aside from Django, are there other equally (or more) popular Python Web frameworks?

**Comment by Walter-0** [comment]
Can you make Django apps with a cursory knowledge of Python, or is it something that requires a decent amount of experience? Also, what's the difference between using Ruby on Rails and Python + Django?
