### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by Curtismn87** [ga-wdi-exercises/sweet-libs#36]
https://github.com/Curtismn87/PHP_tutorial

Comfort: 3/5
Completeness: 4/5

We understand how the code works and how it is used, but we're having trouble actually implementing it.

- Matt and Walter

**Comment by ebirving** [comment]
How accessible did you find the php documentation? What types of additional resources would you like to see to support new PHP developers--and the PHP community at large?

**Comment by Curtismn87** [comment]
So, PHP has been around a while and is kept alive because of it's open source nature. There are a lot of sites that use it and a large community. With that being said finding documentation to apply is kind of difficult because it's a server-side language but if you invest some time there is a lot you can find online on how to use it.

**Comment by jkoul** [comment]
Would you use php and HTML in a page without any further framework? It certainly seems easier than Sinatra or Express, but are there any drawbacks?

**Comment by Curtismn87** [comment]
From what I understood you don't need any further framework when using PHP.. The PHP website is also posted on github. https://github.com/php/web-php .. It looks like the entire thing was written in PHP
