### ISSUE TITLE
Drupal setup instructions

### ISSUE THREAD

**Issue by jkoul** [ga-wdi-exercises/sweet-libs#39]
Github repo: https://github.com/jkoul/groupdrup

Comfort: 2.5

Tom Beach and I worked together to set up a basic site with Drupal. Given that the main draw of Drupal is its reliance on clean packages and plugins/modules,  there wasn't much raw code involved in building the site beyond the command line driven installation and setup. But the readme file in the Github repo does include the detailed steps we took. 

I'm interested in your feedback on the format of the readme and whether the walkthrough is detailed enough.

**Comment by LauraWN** [comment]
It seems detailed enough.
