### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by alexbannon** [ga-wdi-exercises/sweet-libs#4]
Comfort: 5/5
Completeness: 5/5

https://github.com/alexbannon/playing_with_python

**Comment by RobertAKARobin** [comment]
Cool! Out of curiosity, what would make you want to switch from Ruby to Python? Are there any particular applications for which Python is the "way to go"? I'd love to hear more about the difference between this and other languages beyond personal preference. For instance, I know Python is supposed to be "good at math", but I don't know why or how.
