### ISSUE TITLE
Parallax scrolling

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/sweet-libs#42]
https://github.com/LauraWN/TeachMeTeachU

comfort_level: 4
completeness: 4

an example of parallax scrolling code.

**Comment by phantomhaircuts** [comment]
Cooooool! do you see any advantages / disadvantages between using pure css / js parallax?

**Comment by leighvarley** [comment]
I've seen sites like this and wondered how they worked as well! Thanks for the info.
