### ISSUE TITLE
Haml

### ISSUE THREAD

**Issue by silscript** [ga-wdi-exercises/sweet-libs#5]
https://github.com/siltastic/learning-haml

Comfort Level: 4/5
Completeness:  5/5

If I had more time, I would have added more comments and instructions of how to convert your eRuby to Haml. Haml is love.

**Comment by alexbannon** [comment]
If forced to use haml for the rest of your life, what would you be missing out on, say from another markup language like ERB?

**Comment by pdavies88** [comment]
do you feel like HAML would be quicker to use than basic html, it doesn't look like there is much difference other than taking out the tags and replacing them with %. how much does whitespace matter as compared to html where things can be placed oddly and still work?
