### ISSUE TITLE
Python/Django Dom and Eric

### ISSUE THREAD

**Issue by ericcgreen** [ga-wdi-exercises/sweet-libs#74]
Repo: https://github.com/ericcgreen/python/tree/master/text_me

Dom and Eric comfort: 4

Python and Django are powerful tools, I (Eric) wish we spent more time learning this in class over Ruby and Rails.

**Comment by avalant** [comment]
Good job! Python is a very powerful tool and when you combine it with Django -- it becomes even more powerful. Many jobs want proficient python developers so don't let this initial curiosity fall to the wayside -- continue to practice and play around with it.
