### ISSUE TITLE
Melissa & Ksenia - React.js Tutorial

### ISSUE THREAD

**Issue by msteffan** [ga-wdi-exercises/sweet-libs#8]
Comfort: 4
Completeness: 5

Link to Github repo: 
https://github.com/msteffan/ReactTutorial

**Comment by andersenek** [comment]
It worked, yay!
After peeking at your code I noticed in `index.html` the code:
```
<Comment author={comment.author}>
  {comment.text}
</Comment>
```
I was wondering, is this React syntax/convention to display data?

**Comment by karldonus** [comment]
Fascinating! I just attended a meetup with focusing on React and everything was greek to me. Apparently, the inclusion of "flux" is making it a powerful tool that can compete with angular. 
I was thrown off a bit in your readme by going to index.html instead of localhost:3001.
