### ISSUE TITLE
Web Scraper Question

### ISSUE THREAD

**Issue by nrc0004** [ga-wdi-exercises/sweet-libs#88]
We are building a web scraper and it works the first time you deploy it, but then the node server crashes and it cant be used again. Below is our code and the error we get: 

```js
const express = require("express")
const cheerio = require("cheerio")
const request = require("request")
const fs  = require('fs')

const app = express()

app.get('/', function (req, res){

  url = 'https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-1'


  request(url, function(error, response, html){
    if(!error){
      var $ = cheerio.load(html)
      var population
      var json = { population: ""}

      $('#cell51').filter(function(){
        var data = $(this)
        population = data.html()

        json.population = population;
        res.send(population)
      })
    }
  })
})

app.listen('4000')
console.log('Scraping faces on 4k')

exports = module.exports = app
```

------------------------------

Error: 

[nodemon] starting `node index.js`
Scraping faces on 4k
_http_outgoing.js:367
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:367:11)
    at ServerResponse.header (/Users/natashaclark/wdi/Lab/sweet-libs/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/Users/natashaclark/wdi/Lab/sweet-libs/node_modules/express/lib/response.js:170:12)
    at Object.<anonymous> (/Users/natashaclark/wdi/Lab/sweet-libs/index.js:24:13)
    at testFn (/Users/natashaclark/wdi/Lab/sweet-libs/node_modules/cheerio/lib/api/traversing.js:320:22)
    at /Users/natashaclark/wdi/Lab/sweet-libs/node_modules/lodash.filter/index.js:869:9
    at /Users/natashaclark/wdi/Lab/sweet-libs/node_modules/lodash.filter/index.js:1255:11

**Comment by amaseda** [comment]
Hm, is the `.filter` callback executing multiple times? If so, running `res.send( )` might be what's causing that error.

**Comment by nrc0004** [comment]
How would I check if it were firing multiple times? When I try to comment out res.send, it still works in the browser but the server still crashes.

**Comment by nrc0004** [comment]
Hey Adrian, 

Isaac got it, apparently we needed to switch res.send to res.write.

**Comment by amaseda** [comment]
Oh word, awesome!
