### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Ryan-321** [ga-wdi-exercises/sweet-libs#9]
Comfort: 3

Took me awhile to understand conceptual what was going on.  Think I now know, but fuzzy on the details.  Spent more time reading than actually coding.  

Had a hard time finding a good tutorial to follow, tried following two independent ones until I just used the main Reactjs website tutorial.  Should have done that form the get go.  Good learning experience, if I don't have a solid recommendation, follow main one.  

https://github.com/Ryan-321/react

**Comment by cameronfry11** [comment]
Why should I use React over other javascript front end frameworks?
