### ISSUE TITLE
Three.js - Elena Santana

### ISSUE THREAD

**Issue by fanelenan7** [ga-wdi-exercises/sweet-libs#91]
Repo: https://github.com/fanelenan7/threejsPlayground/blob/master/readme.md
Gh-pages: https://fanelenan7.github.io/threejsPlayground/

Comfort score: 4.

Both tetrahedrons have large chunks of code that are pretty much the same... is it possible to make it dry?

**Comment by amaseda** [comment]
Can you point me to the code? Not too familiar with Three.js but hopefully there's a way that doesn't require a knowledge of the library!

:+1:
