### ISSUE TITLE
Lisa Burr - Django/Python

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/sweet-libs#99]
https://github.com/laburr27/sweet-libs

I actually spent the day going through the "Writing your first Django app tutorial"
 [https://docs.djangoproject.com/en/1.10/intro/tutorial01/](url) .

I learned so much more about Django going through the tutorial than if I had gone and tried to throw together some "slap-dash-here-it-is-it-works" app.  I really need the structure and focus when it comes to really LEARNING something new.  If I am modifying or building on something that already exists I can go through the "try this and this and this and OOOOO--what does THIS DO?" dance and learn a lot about a new tech.

Now, if I come across Django in the future I will already have a good basic understanding and familiarity so I will feel comfortable jumping right in on an existing project.

Today was very productive for me though the day turned out to be less about Python and mostly about Django.

**Comment by superbuggy** [comment]
Nice! 👍
